"""expanded schema

Revision ID: 948d85570ae5
Revises: 
Create Date: 2020-12-04 18:07:21.954323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948d85570ae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('workshop_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('container', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True, comment='The port on which the container listens'),
    sa.Column('memory', sa.Text(), nullable=True),
    sa.Column('cpu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_events_email'), 'instance_events', ['email'], unique=False)
    op.create_index(op.f('ix_instance_events_name'), 'instance_events', ['name'], unique=False)
    op.create_index(op.f('ix_instance_events_workshop_id'), 'instance_events', ['workshop_id'], unique=False)
    op.create_table('workshop_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.UniqueConstraint('workshop_id', 'tag_id')
    )
    op.create_index(op.f('ix_workshop_tags_tag_id'), 'workshop_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_workshop_tags_workshop_id'), 'workshop_tags', ['workshop_id'], unique=False)
    op.create_table('workshop_workshop_collections',
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('workshop_collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_collection_id'], ['workshop_collections.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.UniqueConstraint('workshop_id', 'workshop_collection_id')
    )
    op.create_index(op.f('ix_workshop_workshop_collections_workshop_collection_id'), 'workshop_workshop_collections', ['workshop_collection_id'], unique=False)
    op.create_index(op.f('ix_workshop_workshop_collections_workshop_id'), 'workshop_workshop_collections', ['workshop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshop_workshop_collections_workshop_id'), table_name='workshop_workshop_collections')
    op.drop_index(op.f('ix_workshop_workshop_collections_workshop_collection_id'), table_name='workshop_workshop_collections')
    op.drop_table('workshop_workshop_collections')
    op.drop_index(op.f('ix_workshop_tags_workshop_id'), table_name='workshop_tags')
    op.drop_index(op.f('ix_workshop_tags_tag_id'), table_name='workshop_tags')
    op.drop_table('workshop_tags')
    op.drop_index(op.f('ix_instance_events_workshop_id'), table_name='instance_events')
    op.drop_index(op.f('ix_instance_events_name'), table_name='instance_events')
    op.drop_index(op.f('ix_instance_events_email'), table_name='instance_events')
    op.drop_table('instance_events')
    op.drop_table('workshops')
    op.drop_table('workshop_collections')
    op.drop_table('tags')
    # ### end Alembic commands ###
