"""add creation timestable to workshop

Revision ID: cffcab00c8e9
Revises: fc3ffd54d4de
Create Date: 2020-12-10 14:32:19.555934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffcab00c8e9'
down_revision = 'fc3ffd54d4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'created')
    # ### end Alembic commands ###
