"""add name to instances

Revision ID: fc3ffd54d4de
Revises: 97e1b61fb3bd
Create Date: 2020-12-08 09:31:35.554969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3ffd54d4de'
down_revision = '97e1b61fb3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_instances_name'), 'instances', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instances_name'), table_name='instances')
    op.drop_column('instances', 'name')
    # ### end Alembic commands ###
