---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-orchestra-cluster-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-orchestra-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-orchestra-cluster-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-orchestra-cluster-role
subjects:
  - name: workshop-orchestra-sa
    kind: ServiceAccount
    namespace: default
